version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=lucasrusso"
      - "POSTGRES_DB=lucasrusso"
      - "POSTGRES_PASSWORD:lucasrusso"
    expose:
      - "5432"
    ports:
      - "5432:5432"
